services:
  nextjs:
    image: artbocha/foosball-fsk-nextjs:latest
    pull_policy: always
    restart: on-failure
    ports:
      - 3000:3000
    environment:
      - WEBAPP_BACKEND_URL=https://new.rtsf.ru