# set up backend and local front

services:
  nextjs:
    build:
      context: .
    restart: on-failure
    environment:
      - WEBAPP_BACKEND_URL=http://ratings_webapp:8081
  nginx:
    build:
      context: ./nginx
    restart: on-failure
    ports:
      - 3000:80
    environment:
      - WEBAPP_BACKEND_URL=http://ratings_webapp:8081
  postgres:
    image: nkuznetsov44/ratings_storage:latest
    environment:
      POSTGRES_PASSWORD: ratings
      POSTGRES_USER: ratings
      POSTGRES_DB: ratings_core
    volumes:
      - postgresdata:/var/lib/postgresql/data
  ratings_core:
    image: nkuznetsov44/ratings_core:latest
    pull_policy: always
    depends_on:
      - postgres
    restart: on-failure
    ports:
      - 9080:8080
  ratings_webapp:
    image: nkuznetsov44/ratings_webapp:latest
    pull_policy: always
    depends_on:
      - ratings_core
    restart: on-failure
    ports:
      - 9081:8081
volumes:
  postgresdata:
