services:
  nextjs:
    build:
      context: .
    restart: on-failure
  nginx:
    build:
      context: ./nginx
    restart: on-failure
    ports:
      - 3000:80
    environment:
      - WEBAPP_BACKEND_URL="https://new.rtsf.ru"