services:
  nextjs:
    build:
      context: .
    restart: on-failure
    environment:
      - WEBAPP_BACKEND_URL=${WEBAPP_BACKEND_URL}
  nginx:
    build:
      context: ./nginx
    restart: on-failure
    ports:
      - 3000:80
    environment:
      - WEBAPP_BACKEND_URL=${WEBAPP_BACKEND_URL}